### ISSUE TITLE
Instantating new Oauth client 

### ISSUE THREAD

**Issue by Corstiaan84** [evernote/evernote-sdk-ruby#19]
Hi Guys,

Calling "EvernoteOAuth::Client.new(token: self.evernote_auth_token).note_store"

yields this error:

NoMethodError: undefined method `[]' for nil:NilClass
    from /app/vendor/bundle/ruby/2.2.0/gems/evernote_oauth-0.2.3/lib/evernote_oauth/client.rb:18:in`initialize'
    from /app/app/models/seller.rb:89:in `new'
    from /app/app/models/seller.rb:89:in`connect_to_evernote_note_store'
    from /app/app/models/seller.rb:30:in `get_evernote_activator_tag'
    from /app/app/jobs/process_incoming_evernote_request_job.rb:9:in`perform'
    from (irb):4
    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in `start'
    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in`start'
    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in`run_command!'
    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
    from /app/bin/rails:4:in`require'
    from /app/bin/rails:4:in `<main>'

Ideas? :-) thanks!

p.s. All works fine in development...

**Comment by conch** [comment]
It looks like you didn't fill in a config/evernote.yml file with the consumer key and secret.

**Comment by Corstiaan84** [comment]
Ah, indeed. I was missing the production block in the yaml file. Thanks! Mighty be worth raising more descriptive errors though ;-)
